### ISSUE TITLE
Go to web but get a "Not Found"

### ISSUE THREAD

**Issue by travisboss** [hotio/docker-readarr#6]
Not sure how to solve this I use one of your other containers for unpackerr and that loads just fine, but running as compose or running as a `docker run` when I go to the ip:8787 I get nothing.

```
  readarr:
    image: hotio/readarr:unstable
    container_name: readarr
    restart: unless-stopped
    ports:  
      - 8787:8787   
    volumes:    
      - ./readarr:/config      
      - /mnt/media/Books:/books
      - /mnt/media/Audiobooks:/audiobooks
      - /mnt/torrent:/data/downloads/Seeding/Books
    environment:  
      - PUID=${PUID}
      - PGID=${PGID}  
      - TZ=${TZ}
```

Here is the compose config I am using, this is on version "3" if that matters, I also tried changing the port but same error?  I tried enabling `debug` but I did not get any log information besides the service had started.

This is on a raspberry pi 4.
